// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// loopC
NumericVector loopC(NumericVector nodelist, int al, IntegerVector x, IntegerVector x2, List pm_lc, NumericMatrix Lix, int finind);
RcppExport SEXP markophylo_loopC(SEXP nodelistSEXP, SEXP alSEXP, SEXP xSEXP, SEXP x2SEXP, SEXP pm_lcSEXP, SEXP LixSEXP, SEXP finindSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type nodelist(nodelistSEXP);
    Rcpp::traits::input_parameter< int >::type al(alSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< List >::type pm_lc(pm_lcSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Lix(LixSEXP);
    Rcpp::traits::input_parameter< int >::type finind(finindSEXP);
    __result = Rcpp::wrap(loopC(nodelist, al, x, x2, pm_lc, Lix, finind));
    return __result;
END_RCPP
}
// colMeansC
NumericVector colMeansC(NumericMatrix x);
RcppExport SEXP markophylo_colMeansC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    __result = Rcpp::wrap(colMeansC(x));
    return __result;
END_RCPP
}
// cat_loopC
NumericVector cat_loopC(int nocat, NumericVector nodelist, int al, IntegerVector x, IntegerVector x2, List pm_clc, NumericMatrix Lix, int finind);
RcppExport SEXP markophylo_cat_loopC(SEXP nocatSEXP, SEXP nodelistSEXP, SEXP alSEXP, SEXP xSEXP, SEXP x2SEXP, SEXP pm_clcSEXP, SEXP LixSEXP, SEXP finindSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type nocat(nocatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nodelist(nodelistSEXP);
    Rcpp::traits::input_parameter< int >::type al(alSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< List >::type pm_clc(pm_clcSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Lix(LixSEXP);
    Rcpp::traits::input_parameter< int >::type finind(finindSEXP);
    __result = Rcpp::wrap(cat_loopC(nocat, nodelist, al, x, x2, pm_clc, Lix, finind));
    return __result;
END_RCPP
}
// part_loopC
NumericMatrix part_loopC(int nocat, NumericVector nodelist, int al, IntegerVector x, IntegerVector x2, List pm_plc, List Lix, int finind);
RcppExport SEXP markophylo_part_loopC(SEXP nocatSEXP, SEXP nodelistSEXP, SEXP alSEXP, SEXP xSEXP, SEXP x2SEXP, SEXP pm_plcSEXP, SEXP LixSEXP, SEXP finindSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type nocat(nocatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nodelist(nodelistSEXP);
    Rcpp::traits::input_parameter< int >::type al(alSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< List >::type pm_plc(pm_plcSEXP);
    Rcpp::traits::input_parameter< List >::type Lix(LixSEXP);
    Rcpp::traits::input_parameter< int >::type finind(finindSEXP);
    __result = Rcpp::wrap(part_loopC(nocat, nodelist, al, x, x2, pm_plc, Lix, finind));
    return __result;
END_RCPP
}
// expm
arma::mat expm(const arma::mat& M);
RcppExport SEXP markophylo_expm(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    __result = Rcpp::wrap(expm(M));
    return __result;
END_RCPP
}
